### ISSUE TITLE
grafana の最新化

### ISSUE THREAD

**Issue by iganari** [iganari/package-docker-compose#25]
```
version: '3.6'

services:
  grafana:
    # https://grafana.com/grafana/download
    # https://hub.docker.com/r/grafana/grafana
    image: grafana/grafana:9.5.3-ubuntu
    container_name: grafana-basic
    tty: true
    ports:
      - "3000:3000"
    networks:
      - local-network

networks:
  local-network:
```
